### ISSUE TITLE
Improvement ?

### ISSUE THREAD

**Issue by mehdialouafi** [zackify/react-native-autofocus#2]
Hi Zack ! Thanks a lot for this awesome utility ! I was thinking to do it when I found this repo :) 

Sorry I'm not good at giving titles at issues and furthermore this is not an issue but just a suggestion : 

I think that this https://github.com/zackify/react-native-autofocus/blob/master/form.js#L13 needs to be highlight on the repo README.

I'm using your code right now on a project but I wanted to add a wrapper around each TextInput in order to add some ui elements, your recursive part works. However since the line linked above specifies that the component is treated only if it has the TextInput name the code throw an error if that is not the case. The error thrown is 'inputRef is not a function'.

Since the child is returned immediately if it is not named TextInput the inputRef never get declared.

Sorry for my english

**Comment by zackify** [comment]
Yes, I know the problem, i have an issue for it and I'm just getting to it right now.

**Comment by zackify** [comment]
Check the latest release, 0.0.2, should be good
